{
 "title": "SA:MP Servers",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Active Servers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "samplist_index_active" }
   ]
  },
  {
   "title": "Players per Server",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "samplist_index_players/samplist_index_active"
    }
   ]
  },
  {
   "title": "Total Players",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "samplist_index_players" }
   ]
  },
  {
   "title": "Servers",
   "type": "graph",
   "description": "Displays active and inactive servers.\n\nAn inactive server is a server that has been online recently but gone offline. The index will keep tracking the server for a few days but if it remains offline, it will be removed completely.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "samplist_index_active", "legendFormat": "Active" },
    { "expr": "samplist_index_inactive", "legendFormat": "Inactive" }
   ]
  },
  {
   "title": "Total Players",
   "type": "graph",
   "description": "Total amount of online players over time.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "samplist_index_players" }
   ]
  },
  {
   "title": "Query Details",
   "type": "graph",
   "description": "Displays current per-minute rate of all queries, successful queries, failed queries, archived servers and query errors.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(samplist_scraper_queries[1m])",
     "legendFormat": "Queries"
    },
    {
     "expr": "rate(samplist_scraper_failures[1m])",
     "legendFormat": "Failures"
    },
    {
     "expr": "rate(samplist_scraper_successes[1m])",
     "legendFormat": "Successes"
    },
    {
     "expr": "rate(samplist_scraper_archives[1m])",
     "legendFormat": "Archives"
    },
    {
     "expr": "rate(samplist_scraper_removes[1m])",
     "legendFormat": "Removals"
    },
    {
     "expr": "rate(samplist_scraper_errors[1m])",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Average Query Time",
   "type": "graph",
   "description": "Displays the average time each query takes to perform.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "samplist_scraper_query_time{quantile=\"0.99\"}",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "samplist_scraper_query_time{quantile=\"0.9\"}",
     "legendFormat": "90th Percentile"
    }
   ]
  }
 ]
}