type Query {
    Servers(page: Int, sort: String, by: String, filters: [String]): [Server]!
    Server(ip: String): Server!
}

type Server {
    Address: String
    Hostname: String
    Players: Int
    MaxPlayers: Int
    Gamemode: String
    Language: String
    Password: Boolean
    Rules: [Rule]
    Description: String
    Banner: String
}

type Rule {
    Name: String
    Value: String
}
